dependencies:
  - name: postgresql
    version: 0.8.3
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: required_backend.postgresql
  - name: redis
    version: 0.10.1
    condition: required_backend.redis
    repository: https://kubernetes-charts.storage.googleapis.com/
